using Application;
using Domain;

namespace Infrastructure.Test;

public class YerevanCityCheckJsonParserTest
{
    [Fact]
    public void All_Parsed_Expenses_Have_The_Same_Date()
    {
        var text = GetStringJson();
        
        var expenses = ParseExpenses(text);

        Assert.True(expenses.All(c => c.Date == new DateOnly(2022, 07, 13)));
        
        var sum = expenses.Select(c => c.Amount).Aggregate((a, b) => a + b);
        
        Assert.Equal(new Money(){Amount = 17240.67m, Currency = Currency.AMD}, sum);
    }
    
    [Fact]
    public void All_Parsed_Expenses_Have_Prefix()
    {
        var text = GetStringJson();
        
        var expenses = ParseExpenses(text);

        Assert.True(expenses.All(c => c.Description.StartsWith("Ереван-сити:")));
    }

    private static string GetStringJson()
    {
        var text = @"
{
    ""success"":  true,
    ""data"":  {
                 ""orderId"":  ""DM0000500829"",
                 ""createDate"":  ""2022-07-13T16:25:44"",
                 ""paymentMethod"":  2,
                 ""usedBonusAmount"":  0,
                 ""deliveryPrice"":  0,
                 ""totalPrice"":  17241.0,
                 ""status"":  7,
                 ""totalToPay"":  17241.0,
                 ""shopUserId"":  ""353e3220-d8f0-49ca-821e-280a48940847"",
                 ""name"":  ""Andrew"",
                 ""surName"":  ""Ivanov"",
                 ""photo"":  null,
                 ""phoneNumber"":  ""+37444242205"",
                 ""orderItems"":  [
                                    {
                                        ""id"":  2069,
                                        ""name"":  ""Сыр моцарелла \""Борисовка\"" 200г"",
                                        ""price"":  1195,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1054101.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Feta,brined, bryndza, mozzarella cheeses"",
                                        ""codeSap"":  1054101,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  5975,
                                        ""weightProductPricePerUnit"":  200,
                                        ""weightMeasure"":  ""G""
                                    },
                                    {
                                        ""id"":  4741,
                                        ""name"":  ""Хлопья овс. Рус.Продукт Гер. нежный 450г"",
                                        ""price"":  509.98,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1068464.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Oat flakes, Hercules"",
                                        ""codeSap"":  1068464,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  1133,
                                        ""weightProductPricePerUnit"":  450,
                                        ""weightMeasure"":  ""G""
                                    },
                                    {
                                        ""id"":  6432,
                                        ""name"":  ""Т/Б \""Zewa\"" Плюс 2x сл. 4шт"",
                                        ""price"":  559.98,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1029411.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Toilet paper"",
                                        ""codeSap"":  1029411,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  139,
                                        ""weightProductPricePerUnit"":  4,
                                        ""weightMeasure"":  ""PC""
                                    },
                                    {
                                        ""id"":  7173,
                                        ""name"":  ""Макароны-бантики \""Макфа\"" 400г"",
                                        ""price"":  580,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1038276.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Pasta"",
                                        ""codeSap"":  1038276,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  1450,
                                        ""weightProductPricePerUnit"":  400,
                                        ""weightMeasure"":  ""G""
                                    },
                                    {
                                        ""id"":  14069,
                                        ""name"":  ""Окрошка \""Биокат\"" 500г"",
                                        ""price"":  300,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1087471.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Okroshka"",
                                        ""codeSap"":  1087471,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  600,
                                        ""weightProductPricePerUnit"":  500,
                                        ""weightMeasure"":  ""G""
                                    },
                                    {
                                        ""id"":  14361,
                                        ""name"":  ""Шок. конфеты \""Bounty\"" Minis кг"",
                                        ""price"":  1068.72,
                                        ""initialPrice"":  0,
                                        ""quantity"":  0,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1056817.png"",
                                        ""weight"":  282,
                                        ""isKilogram"":  true,
                                        ""minimumWeight"":  200,
                                        ""weightStep"":  200,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  282,
                                        ""initialQuantity"":  0,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Chocolate candies"",
                                        ""codeSap"":  1056817,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  null,
                                        ""weightProductPricePerUnit"":  1000,
                                        ""weightMeasure"":  ""NO""
                                    },
                                    {
                                        ""id"":  16233,
                                        ""name"":  ""Молоко \""Чанах\"" 3.2% 950мл"",
                                        ""price"":  510,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1036477.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Milk"",
                                        ""codeSap"":  1036477,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  536,
                                        ""weightProductPricePerUnit"":  950,
                                        ""weightMeasure"":  ""ML""
                                    },
                                    {
                                        ""id"":  21245,
                                        ""name"":  ""Гречка кг"",
                                        ""price"":  178.51,
                                        ""initialPrice"":  0,
                                        ""quantity"":  0,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1038287.png"",
                                        ""weight"":  238,
                                        ""isKilogram"":  true,
                                        ""minimumWeight"":  500,
                                        ""weightStep"":  100,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  238,
                                        ""initialQuantity"":  0,
                                        ""initialCount"":  0,
                                        ""isOnline"":  false,
                                        ""categoryName"":  ""Buckwheat"",
                                        ""codeSap"":  1038287,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  null,
                                        ""weightProductPricePerUnit"":  null,
                                        ""weightMeasure"":  null
                                    },
                                    {
                                        ""id"":  26981,
                                        ""name"":  ""Крупа манная \""Кубань-Матушка\"" 800г"",
                                        ""price"":  490,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1103764.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  false,
                                        ""categoryName"":  ""Grain"",
                                        ""codeSap"":  1103764,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  612,
                                        ""weightProductPricePerUnit"":  800,
                                        ""weightMeasure"":  ""G""
                                    },
                                    {
                                        ""id"":  32209,
                                        ""name"":  ""Кур.грудинка св. \""Аштарак\"" тар. 950г"",
                                        ""price"":  2100,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1097928.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Fresh chicken"",
                                        ""codeSap"":  1097928,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  2210,
                                        ""weightProductPricePerUnit"":  950,
                                        ""weightMeasure"":  ""G""
                                    },
                                    {
                                        ""id"":  50906,
                                        ""name"":  ""Орех Макадамия кг"",
                                        ""price"":  1518.48,
                                        ""initialPrice"":  0,
                                        ""quantity"":  0,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1085022.png"",
                                        ""weight"":  152,
                                        ""isKilogram"":  true,
                                        ""minimumWeight"":  250,
                                        ""weightStep"":  250,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  152,
                                        ""initialQuantity"":  0,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Nuts"",
                                        ""codeSap"":  1085022,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  null,
                                        ""weightProductPricePerUnit"":  1000,
                                        ""weightMeasure"":  ""NO""
                                    },
                                    {
                                        ""id"":  67249,
                                        ""name"":  ""Яйца \""Арзни\"" лаваш дзу #0-2 10шт"",
                                        ""price"":  550,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1112263.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Eggs 10pcs"",
                                        ""codeSap"":  1112263,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  55,
                                        ""weightProductPricePerUnit"":  10,
                                        ""weightMeasure"":  ""PC""
                                    },
                                    {
                                        ""id"":  81152,
                                        ""name"":  ""Пакет полиэт. \""Yerevan City\"" 50mc сред."",
                                        ""price"":  100,
                                        ""initialPrice"":  0,
                                        ""quantity"":  2,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1122223.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  true,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  2,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Plastic packets"",
                                        ""codeSap"":  1122223,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  null,
                                        ""weightProductPricePerUnit"":  1,
                                        ""weightMeasure"":  ""NO""
                                    },
                                    {
                                        ""id"":  89478,
                                        ""name"":  ""Соевый соус \""Такемура\"" 1л"",
                                        ""price"":  1370,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1126902.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  false,
                                        ""categoryName"":  ""Sauces for sushi and Asian cuisine"",
                                        ""codeSap"":  1126902,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  null,
                                        ""weightProductPricePerUnit"":  1000,
                                        ""weightMeasure"":  ""NO""
                                    },
                                    {
                                        ""id"":  90121,
                                        ""name"":  ""Рис длиннозерный \""От Гурмана\"" 450г"",
                                        ""price"":  460,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1127313.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  true,
                                        ""categoryName"":  ""Rice"",
                                        ""codeSap"":  1127313,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  1022,
                                        ""weightProductPricePerUnit"":  450,
                                        ""weightMeasure"":  ""G""
                                    },
                                    {
                                        ""id"":  91596,
                                        ""name"":  ""Соус \""Тамаки\"" ореховый 470мл"",
                                        ""price"":  3090,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1128543.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  false,
                                        ""categoryName"":  ""Sauces for sushi and Asian cuisine"",
                                        ""codeSap"":  1128543,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  null,
                                        ""weightProductPricePerUnit"":  null,
                                        ""weightMeasure"":  null
                                    },
                                    {
                                        ""id"":  91601,
                                        ""name"":  ""Соус \""Тамаки\"" чили с ананасом 470мл"",
                                        ""price"":  2660,
                                        ""initialPrice"":  0,
                                        ""quantity"":  1,
                                        ""note"":  null,
                                        ""photo"":  ""https://media.yerevan-city.am/api/Image/Resize/ProductPhoto/1128548.png"",
                                        ""weight"":  0,
                                        ""isKilogram"":  false,
                                        ""minimumWeight"":  null,
                                        ""weightStep"":  null,
                                        ""visiblePrice"":  1000,
                                        ""bonus"":  0.0,
                                        ""cut"":  false,
                                        ""grind"":  false,
                                        ""totalPrice"":  0,
                                        ""isBag"":  false,
                                        ""initialWeight"":  0,
                                        ""initialQuantity"":  1,
                                        ""initialCount"":  0,
                                        ""isOnline"":  false,
                                        ""categoryName"":  ""Hot sauces"",
                                        ""codeSap"":  1128548,
                                        ""attributes"":  null,
                                        ""productTag"":  null,
                                        ""productPricePerUnit"":  5659,
                                        ""weightProductPricePerUnit"":  470,
                                        ""weightMeasure"":  ""ML""
                                    }
                                ],
                 ""totalBonus"":  0.0,
                 ""branchAddress"":  {
                                       ""address"":  ""3 Tsitsernakaberd Hwy, Yerevan 0082, Armenia"",
                                       ""id"":  ""DL09""
                                   }
             },
    ""messages"":  [
                     {
                         ""key"":  1,
                         ""value"":  ""OK""
                     }
                 ],
    ""alertIcon"":  null
}";
        return text;
    }

    private static List<Outcome> ParseExpenses(string text)
    {
        var parser = new YerevanCityExpenseJsonParser(new ExternalCategoryMapper());
        
        return parser.ParseOutcomes(text, Categories.Outcome.DefaultCategory).ToList();
    }
}